export const UPDATE_ITEMS = 'UPDATE_ITEMS'
export const ADD_ATTRIBUTE = 'ADD_ATTRIBUTE'
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'
export const UPDATE_ITEM_ATTRIBUTE_VALUE = 'UPDATE_ITEM_ATTRIBUTE_VALUE'